Algoritmo "antecessor"
// Descrição   : Imprime o antecessor
// Autor(a)    : Giovanna
Var
// Seção de Declarações das variáveis
valor, antecessor : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreval("Insira um número para retornar o antecessor deste: ")
leia(valor)

antecessor <- valor - 1

escreval("O antecessor de", valor," é igual a: ", antecessor)

Fimalgoritmo