Algoritmo "semnome"
// Descrição   : Cálculo de área
// Autor(a)    : Giovanna
Var
// Seção de Declarações das variáveis 
area, base, altura : real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval(">>>Cálculo da área<<<")
escreval("Insira a base: ")
leia(base)
escreval("Insira a altura: ")
leia(altura)

area <- base * altura

escreval("Área = ", area)

Fimalgoritmo